### ISSUE TITLE
uninitialized constant WIN32OLE

### ISSUE THREAD

**Issue by obazoud** [chef-cookbooks/chef-client#212]
In my base cookbook, I include these chef-client recipes in 'base::chef_client'

base::chef_client.rb

```
include_recipe 'chef-client::config'
include_recipe 'chef-client::default'
include_recipe 'chef-client::delete_validation'
```

In chef spec:

```
describe 'base::install on windows 2012' do
  let(:chef_run) do
    ChefSpec::Runner.new(
      platform: 'windows',
      version: '2012'
    ) do |node|
      node.set['base']['xxx'] = 'xxx'
    end.converge('base::install')
  end

  context 'when using install recipe' do
    it 'includes other recipe' do
      expect(chef_run).to include_recipe('base::chef_client')
    end
  end
end
```

Got this error with chefspec

```
 ================================================================================
Recipe Compile Error in /tmp/d20141030-8188-17chp5p/cookbooks/base/recipes/install.rb
================================================================================

NameError
---------
uninitialized constant WIN32OLE

Cookbook Trace:
---------------
  /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:42:in `wmi_property_from_query'
  /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:54:in `root_owner'
  /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:64:in `dir_owner'
  /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:90:in `create_directories'
  /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/recipes/config.rb:49:in `from_file'
  /tmp/d20141030-8188-17chp5p/cookbooks/base/recipes/chef_client.rb:3:in `from_file'
  /tmp/d20141030-8188-17chp5p/cookbooks/base/recipes/install.rb:13:in `from_file'

Relevant File Content:
----------------------
/tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:

 35:            Chef::Log.debug("Node has Chef Server Executable? #{system("which chef-server > /dev/null 2>&1")}") # ~FC048 Prefer Mixlib::ShellOut is ignored here
 36:            Chef::Log.debug("Node has Chef Server Ctl Executable? #{system("which chef-server-ctl > /dev/null 2>&1")}") # ~FC048 Prefer Mixlib::ShellOut is ignored here
 37:            node.recipe?('chef-server') || system('which chef-server > /dev/null 2>&1') || system('which chef-server-ctl > /dev/null 2>&1') # ~FC048 Prefer Mixlib::ShellOut is ignored here
 38:          end
 39:        end
 40:  
 41:        def wmi_property_from_query(wmi_property, wmi_query)
 42>>         @wmi = ::WIN32OLE.connect("winmgmts://")
 43:          result = @wmi.ExecQuery(wmi_query)
 44:          return nil unless result.each.count > 0
 45:          result.each.next.send(wmi_property)
 46:        end
 47:  
 48:        def chef_client_service_running
 49:          wmi_property_from_query(:name, "select * from Win32_Service where name = 'chef-client'") != nil
 50:        end
 51:  

F/tmp/d20141030-8188-17chp5p/cookbooks/omnibus_updater/libraries/omnitrucker.rb:3: warning: already initialized constant URL_MAP
[2014-10-30T11:50:59+01:00] WARN: Cloning resource attributes for service[chef-client] from prior resource (CHEF-3694)
[2014-10-30T11:50:59+01:00] WARN: Previous service[chef-client]: /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/recipes/init_service.rb:32:in `from_file'
[2014-10-30T11:50:59+01:00] WARN: Current  service[chef-client]: /tmp/d20141030-8188-17chp5p/cookbooks/omnibus_updater/recipes/installer.rb:9:in `from_file'
.

Failures:

  1) base::install on centos 6.5 when using install recipe includes other recipe
     Failure/Error: ChefSpec::Runner.new(
     TypeError:
       can't convert nil into String
     # /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/recipes/delete_validation.rb:28:in `exists?'
     # /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/recipes/delete_validation.rb:28:in `block (2 levels) in from_file'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource/conditional.rb:86:in `call'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource/conditional.rb:86:in `evaluate_block'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource/conditional.rb:75:in `evaluate'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource/conditional.rb:66:in `continue?'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource.rb:713:in `block in should_skip?'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource.rb:712:in `each'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource.rb:712:in `find'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource.rb:712:in `should_skip?'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chefspec-4.0.2/lib/chefspec/extensions/chef/resource.rb:19:in `run_action'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/runner.rb:49:in `run_action'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/runner.rb:81:in `block (2 levels) in converge'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/runner.rb:81:in `each'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/runner.rb:81:in `block in converge'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/resource_collection.rb:96:in `execute_each_resource'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/runner.rb:80:in `converge'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/client.rb:345:in `converge'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chefspec-4.0.2/lib/chefspec/runner.rb:130:in `converge'
     # ./spec/unit/default/install_spec.rb:6:in `block (2 levels) in <top (required)>'
     # ./spec/unit/default/install_spec.rb:16:in `block (3 levels) in <top (required)>'

  2) base::install on windows 2012 when using install recipe includes other recipe
     Failure/Error: ChefSpec::Runner.new(
     NameError:
       uninitialized constant WIN32OLE
     # /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:42:in `wmi_property_from_query'
     # /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:54:in `root_owner'
     # /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:64:in `dir_owner'
     # /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/libraries/helpers.rb:90:in `create_directories'
     # /tmp/d20141030-8188-17chp5p/cookbooks/chef-client/recipes/config.rb:49:in `from_file'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `from_file'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/cookbook_version.rb:234:in `load_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:166:in `load_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:135:in `block in include_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:134:in `each'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:134:in `include_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
     # /tmp/d20141030-8188-17chp5p/cookbooks/base/recipes/chef_client.rb:3:in `from_file'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `from_file'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/cookbook_version.rb:234:in `load_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:166:in `load_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:135:in `block in include_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:134:in `each'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:134:in `include_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
     # /tmp/d20141030-8188-17chp5p/cookbooks/base/recipes/install.rb:13:in `from_file'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `instance_eval'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/mixin/from_file.rb:30:in `from_file'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/cookbook_version.rb:234:in `load_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:166:in `load_recipe'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/run_context.rb:89:in `load'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chef-11.16.2/lib/chef/client.rb:265:in `setup_run_context'
     # /home/obazoud/.rvm/gems/ruby-1.9.3-p550/gems/chefspec-4.0.2/lib/chefspec/runner.rb:124:in `converge'
     # ./spec/unit/default/install_spec.rb:25:in `block (2 levels) in <top (required)>'
     # ./spec/unit/default/install_spec.rb:35:in `block (3 levels) in <top (required)>'
```

See #176

Any tips ?

**Comment by mcascone** [comment]
This may have changed since the previous comment, as I'm able to test Windows cookbooks from a Linux machine, and hadn't had a problem with it until I added the `chef-client` cookbook to my recipes. Now they throw the `uninitialized constant WIN32OLE` error when testing from Linux. I've started a discussion/question on how to stub the right thing to get it work on linux in the https://github.com/sethvargo/chefspec/issues/405 issue.

**Comment by shoekstra** [comment]
@mcascone I encountered similar but was not able to remove this cookbook as it's part of our base role cookbook.  To get around that error in my base role cookbook I did the following:

in `./spec/spec_helper.rb`:

```
# Load additional stub stuff when tests are not running on Windows
unless RUBY_PLATFORM =~ /mswin|mingw32|windows/
  $LOAD_PATH.unshift(
    File.expand_path(
      File.join(File.dirname(__FILE__), 'stubs')
    )
  )
  require 'win32ole'
end
```

in `./spec/stubs/win32ole.rb`:

```
class WIN32OLE
  def self.connect(_name)
    Class.new do
      def self.ExecQuery(_name)
        []
      end
    end
  end
end
```

Disclaimer: I'm no Rubyist and this feels very hacky, but I had seen similar for `Win32/registry` and `Win32/service` so thought I would try do the same for `win32ole` and it seems to work.

Hope that helps you.

**Comment by coderanger** [comment]
You can do this way less hackily:

```ruby
before do
  stub_const('WIN32OLE', Module.new) unless defined?(WIN32OLE)
  allow(WIN32OLE).to receive(:connect).and_return(double(ExecQuery: []))
end
```
