### ISSUE TITLE
Windows chef-client service issues (ruby.exe memory leak?)

### ISSUE THREAD

**Issue by mathewcrane** [chef-cookbooks/chef-client#403]
### Cookbook version
chef-client 4.3.2
windows 1.39.2

### Chef-client version
chef 11.18.0

### Platform Details
Windows Server 2012, latest patchset

### Scenario:
- chef-client windows service runs start failing with a thread error: 'ThreadError: can't create thread (12)'
- ruby.exe using close to 2G RAM
- attempting to restart service via Windows service manager (services.msc) or chef-service-manager stop hangs, requires taskkill /F
- requires manual kill of ruby.exe, and manual restart of service

### Steps to Reproduce:
- Start chef-client service.. wait a while

### Expected Result:
- chef-client service runs without issue

### Actual Result:
- chef-client service eventually fails with error:

```
[2016-06-01T07:59:36+00:00] INFO: *** Chef 11.18.0 ***
[2016-06-01T07:59:36+00:00] INFO: Chef-client pid: 888
[2016-06-01T08:00:17+00:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2016-06-01T08:00:19+00:00] ERROR: ThreadError: can't create Thread (12)
[2016-06-01T08:00:19+00:00] ERROR: Sleeping for 1800 seconds before trying again
```

```
Generated at 2016-06-01 15:08:03 +0000
ThreadError: can't create Thread (12)
C:/opscode/chef/embedded/lib/ruby/1.9.1/timeout.rb:60:in `start'
C:/opscode/chef/embedded/lib/ruby/1.9.1/timeout.rb:60:in `timeout'
C:/opscode/chef/embedded/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
C:/opscode/chef/embedded/lib/ruby/1.9.1/net/http.rb:763:in `connect'
C:/opscode/chef/embedded/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
C:/opscode/chef/embedded/lib/ruby/1.9.1/net/http.rb:745:in `start'
C:/opscode/chef/embedded/lib/ruby/1.9.1/net/http.rb:1285:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/rest-client-1.6.7/lib/restclient/net_http_ext.rb:51:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/http/basic_client.rb:65:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/http.rb:262:in `block in send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/http.rb:294:in `block in retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/http.rb:292:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/http.rb:292:in `retrying_http_errors'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/http.rb:256:in `send_http_request'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/http.rb:143:in `request'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/rest.rb:115:in `get'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/node.rb:508:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/node.rb:492:in `find_or_create'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/policy_builder/expand_node_object.rb:92:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/client.rb:249:in `load_node'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/client.rb:418:in `do_run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/client.rb:227:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/application.rb:236:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/application/client.rb:338:in `block in run_application'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/application/client.rb:327:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/application/client.rb:327:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/lib/chef/application.rb:55:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.18.0-x86-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:23:in `load'
C:/opscode/chef/bin/chef-client:23:in `<main>'
```

What are other people doing in Windows? 
Should I migrate to a scheduled task run?

**Comment by tas50** [comment]
There's a few things you can do to improve things here.  The first is ideally you run as a scheduled task.  There are memory leaks in Ruby on Windows that will eventually bloat the system when you run it as a system. Using scheduled tasks avoid having that long running process. The other thing you can do is upgrade from Chef 11 to Chef 12 which includes updated Ruby to resolve some of those issues.
