### ISSUE TITLE
Chef-Solo fails in 12.11.18 if duplicate cookbooks on path

### ISSUE THREAD

**Issue by arothian** [chef-cookbooks/chef-client#408]
### Chef-client version
12.11.18

### Platform Details
Ubuntu 12.04 - AWS EC2

### Scenario:
Running chef-solo

### Steps to Reproduce:
Run chef-solo with a cookbook path that contains duplicate cookbooks in different directories.

### Expected Result:
The run completes successfully (it works in --legacy-mode) or an appropriate error message occurs.

### Actual Result:
```
[2016-06-10T18:20:55+00:00] ERROR: #<NameError: undefined local variable or method `seen' for #<Chef::ChefFS::FileSystem::MultiplexedDir:0x00000003d3d238>>
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/multiplexed_dir.rb:44:in `block in make_child_entry'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/multiplexed_dir.rb:40:in `each'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/multiplexed_dir.rb:40:in `make_child_entry'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system/base_fs_object.rb:103:in `child'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system.rb:103:in `block in resolve_path'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system.rb:102:in `each'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/file_system.rb:102:in `resolve_path'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/chef_fs_data_store.rb:828:in `get_single_cookbook_version'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-12.11.18/lib/chef/chef_fs/chef_fs_data_store.rb:549:in `list'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:83:in `block in list'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:113:in `fix_exceptions'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/data_store/v1_to_v2_adapter.rb:82:in `list'
/usr/local/rvm/gems/ruby-2.1.10/gems/chef-zero-4.6.2/lib/chef_zero/rest_base.rb:99:in `list_data'
...
```

**Comment by tas50** [comment]
This looks like a bug in the chef-client itself not the cookbook for chef client. Please open up the bug at https://github.com/chef/chef
