### ISSUE TITLE
task recipe fails to converge

### ISSUE THREAD

**Issue by KirkMartinez** [chef-cookbooks/chef-client#417]
After the converge failure, I tried to run schtask manually and got more info:

```
PS C:\Windows\system32> schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "30" /ST "07:59" /TR "cmd /c \\" C:/opsco
de/chef/bin/chef-client -L C:/chef/client.log -c C:/chef/client.rb -s 300 > NUL 2>&1\\"" /RU "SYSTEM" /RL "HIGHEST"
Redirection to 'NUL' failed: FileStream will not open Win32 devices such as disk partitions and tape drives. Avoid use
of "\\.\" in the path.
At line:1 char:172
+ schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "30" /ST "07:59" /TR "cmd /c \\" C:/opscode/chef/bin/chef-clie
nt -L C:/chef/client.log -c C:/chef/client.rb -s 300 > <<<<  NUL 2>&1\\"" /RU "SYSTEM" /RL "HIGHEST"
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : RedirectionFailed
```

I was able to get the schtask to install manually by quoting the > using ^ (and tweaking the quoting):

```
PS C:\Windows\system32> schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "30" /ST "07:59" /TR "cmd /c \" C:/opscod
e/chef/bin/chef-client -L C:/chef/client.log -c C:/chef/client.rb -s 300 ^> NUL 2>&1\"" /RU "SYSTEM" /RL "HIGHEST"
SUCCESS: The scheduled task "chef-client" has successfully been created.
```

### Cookbook version
5.0.0 (also 4.5.0)

### Chef-client version
12.12.15

### Platform Details
Windows 7 SP1

### Scenario:
Using a cookbook wrapper around chef-client which just
node.default['chef_client']['log_dir'] = 'C:/chef'
include_recipe 'chef-client::task'

### Steps to Reproduce:
Include wrapper cookbook above in a recipe used by the node.

### Expected Result:
A scheduled task to run chef-client be installed.

### Actual Result:
Converge yields:
```
  * windows_task[chef-client] action create[2016-08-09T07:29:15-07:00] INFO: Processing windows_task[chef-client] action
 create (chef-client::task line 46)


    ================================================================================
    Error executing action `create` on resource 'windows_task[chef-client]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '-2147467259'
    ---- Begin output of schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "30" /ST "07:59" /TR "cmd /c \\" C:/opsc
ode/chef/bin/chef-client -L C:/chef/client.log -c C:/chef/client.rb -s 300 > NUL 2>&1\\"" /RU "SYSTEM" /RL "HIGHEST"  --
--
    STDOUT:
    STDERR:
    ---- End output of schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "30" /ST "07:59" /TR "cmd /c \\" C:/opscod
e/chef/bin/chef-client -L C:/chef/client.log -c C:/chef/client.rb -s 300 > NUL 2>&1\\"" /RU "SYSTEM" /RL "HIGHEST"  ----

    Ran schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "30" /ST "07:59" /TR "cmd /c \\" C:/opscode/chef/bin/chef
-client -L C:/chef/client.log -c C:/chef/client.rb -s 300 > NUL 2>&1\\"" /RU "SYSTEM" /RL "HIGHEST"  returned -214746725
9

    Cookbook Trace:
    ---------------
    c:/chef/cache/cookbooks/windows/providers/task.rb:183:in `run_schtasks'
    c:/chef/cache/cookbooks/windows/providers/task.rb:55:in `block in class_from_file'
    c:/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/chef-client/recipes/task.rb

     46: windows_task 'chef-client' do
     47:   run_level :highest
     48:   command "cmd /c \\\"#{client_cmd} > NUL 2>&1\\\""
     49:
     50:   user               node['chef_client']['task']['user']
     51:   password           node['chef_client']['task']['password']
     52:   frequency          node['chef_client']['task']['frequency'].to_sym
     53:   frequency_modifier node['chef_client']['task']['frequency_modifier']
     54:   start_time         node['chef_client']['task']['start_time'] || start_time
     55: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/chef-client/recipes/task.rb:46:in `from_file'

    windows_task("chef-client") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :windows_task
      cookbook_name "chef-client"
      recipe_name "task"
      run_level :highest
      command "cmd /c \\\" C:/opscode/chef/bin/chef-client -L C:/chef/client.log -c C:/chef/client.rb -s 300 > NUL 2>&1\
\\""
      user "SYSTEM"
      frequency :minute
      frequency_modifier 30
      start_time "07:59"
      task_name "chef-client"
    end

    Platform:
    ---------
    x64-mingw32
```

**Comment by stractenberg-sps** [comment]
Thankfully I'm not the only one. Worked on this ALL DAY yesterday to no avail thinking I was doing something wrong. Subscribed...

**Comment by maraca** [comment]
+1.
Same here, locking down to previous version.

**Comment by jeremymv2** [comment]
Please @everyone maybe verify the #422 branch works for you so that we can get this merged?
Thanks! :)
