### ISSUE TITLE
chef-client - undefined method 'property' for Chef::Resource::LogrotateApp:Class

### ISSUE THREAD

**Issue by egadgetjnr** [chef-cookbooks/chef-client#501]
### Cookbook version
chef-client 8.1.2
compat_resource (12.19.0)
cron (4.1.3)
logrotate (2.2.0)
ohai (5.1.0)
windows (3.1.1)

### Chef-client version
12.19.36

### Platform Details
Ubuntu 16.04

### Scenario:
chef-client does not run due to an issues with the `chef-client::default recipe`

### Steps to Reproduce:
Add the recipe `"chef-client::default", "chef-client::delete_validation"` to the run-list.
run `sudo chef-client`

### Expected Result:
the chef-client should run and periodically run the chef-client

### Actual Result:
```
Starting Chef Client, version 12.3.0
resolving cookbooks for run list: ["chef-client::default"]
Synchronizing Cookbooks:
  - cron
  - chef-client
  - ohai
  - compat_resource
  - logrotate
  - windows
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/logrotate/resources/app.rb
================================================================================

NoMethodError
-------------
undefined method 'property' for Chef::Resource::LogrotateApp:Class

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/logrotate/resources/app.rb:19:in `class_from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:50:in `build_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/logrotate/resources/app.rb:

 12:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 13:  # See the License for the specific language governing permissions and
 14:  # limitations under the License.
 15:  #
 16:
 17:  resource_name :logrotate_app
 18:
 19>> property :path, [String, Array], required: true
 20:  property :frequency, String, default: 'weekly'
 21:  property :cookbook, default: 'logrotate'
 22:  property :template_name, default: 'logrotate.erb'
 23:  property :template_mode, default: '0644'
 24:  property :template_owner, default: 'root'
 25:  property :template_group, default: 'root'
 26:  property :base_dir, String, default: '/etc/logrotate.d'
 27:
 28:  property :options, [Array, String], default: %w(missingok compress delaycompress copytruncate notifempty)


Running handlers:
[2017-06-21T10:29:01+10:00] ERROR: Running exception handlers
Running handlers complete
[2017-06-21T10:29:01+10:00] ERROR: Exception handlers complete
[2017-06-21T10:29:01+10:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.03947221 seconds
[2017-06-21T10:29:01+10:00] ERROR: undefined method `property' for Chef::Resource::LogrotateApp:Class
[2017-06-21T10:29:01+10:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by jhazelwo-charter** [comment]
You need to upgrade your Chef client.

**Comment by tas50** [comment]
Your logs show chef-client 12.3, which won't work with that version of the logrotate cookbook. Either you need to pin to an older version or upgrade your client. Chef 12.3 came out in April of 2015 and we've improved a huge number of things since then. I'd highly recommend upgrading at least to the last release of Chef 12. You'll get support for custom resources which is why this is failing, plus you'll get tons of other new resources and fixes.
