### ISSUE TITLE
Running chef-client cookbook on Windows 10 produces an "invalid date" error.

### ISSUE THREAD

**Issue by billmeyer** [chef-cookbooks/chef-client#523]
### Cookbook version
8.1.8

### Chef-client version
13.4.24

### Platform Details
Windows 10 Pro - Version 1703

### Scenario:
Add the chef-client cookbook to the run list for a Windows 10 node.

### Steps to Reproduce:
Getting an "invalid date" error when running chef-client as Administrator on Windows 10 via a PowerShell prompt.

### Expected Result:
The chef-client cookbook to complete without issuing an "invalid date" error.

### Actual Result:

```
PS C:\WINDOWS\system32> chef-client
Starting Chef Client, version 13.4.24
[2017-09-18T16:24:21-05:00] INFO: *** Chef 13.4.24 ***
[2017-09-18T16:24:21-05:00] INFO: Platform: x64-mingw32
[2017-09-18T16:24:21-05:00] INFO: Chef-client pid: 11496
[2017-09-18T16:24:21-05:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
[2017-09-18T16:24:24-05:00] INFO: Run List is [role[base_windows10]]
[2017-09-18T16:24:24-05:00] INFO: Run List expands to [chef-client, base_windows10, audit]
[2017-09-18T16:24:24-05:00] INFO: Starting Chef Run for wpc1
[2017-09-18T16:24:24-05:00] INFO: Running start handlers
[2017-09-18T16:24:24-05:00] INFO: Start handlers complete.
resolving cookbooks for run list: ["chef-client", "base_windows10", "audit"]
[2017-09-18T16:24:24-05:00] INFO: Loading cookbooks [chef-client@8.1.8, cron@4.1.1, compat_resource@12.19.0, logrotate@2.1.0, windows@3.1.1, ohai@5.1.0, base_windows10@0.1.2, windows_rdp@0.1.1, audit@5
.0.0]
Synchronizing Cookbooks:
  - chef-client (8.1.8)
  - cron (4.1.1)
  - compat_resource (12.19.0)
  - logrotate (2.1.0)
  - windows (3.1.1)
  - ohai (5.1.0)
  - base_windows10 (0.1.2)
  - windows_rdp (0.1.1)
  - audit (5.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
[2017-09-18T16:24:24-05:00] INFO: Found chef-client in C:/opscode/chef/bin/chef-client
Recipe: audit::inspec
  * inspec_gem[inspec] action install[2017-09-18T16:24:25-05:00] INFO: Processing inspec_gem[inspec] action install (audit::inspec line 20)
[2017-09-18T16:24:25-05:00] INFO: Installation of InSpec required: false
[2017-09-18T16:24:25-05:00] INFO: inspec_gem: not installing InSpec. It's already installed or an explicit version was not supplied.
 (up to date)
[2017-09-18T16:24:25-05:00] INFO: loading handler from c:/chef/cache/cookbooks/audit/files/default/handler/audit_report
  Converging 4 resources
Recipe: chef-client::task
  * windows_service[chef-client] action configure_startup[2017-09-18T16:24:25-05:00] INFO: Processing windows_service[chef-client] action configure_startup (chef-client::task line 31)
 (skipped due to only_if)
  * chef_client_scheduled_task[Chef Client] action add[2017-09-18T16:24:25-05:00] INFO: Processing chef_client_scheduled_task[Chef Client] action add (chef-client::task line 37)

    * directory[C:/chef/run] action create[2017-09-18T16:24:25-05:00] INFO: Processing directory[C:/chef/run] action create (c:/chef/cache/cookbooks/chef-client/libraries/helpers.rb line 56)
 (up to date)
    * directory[C:/chef/cache] action create[2017-09-18T16:24:25-05:00] INFO: Processing directory[C:/chef/cache] action create (c:/chef/cache/cookbooks/chef-client/libraries/helpers.rb line 56)
 (up to date)
    * directory[C:/chef/backup] action create[2017-09-18T16:24:25-05:00] INFO: Processing directory[C:/chef/backup] action create (c:/chef/cache/cookbooks/chef-client/libraries/helpers.rb line 56)
 (up to date)
    * directory[C:/chef/log] action create[2017-09-18T16:24:25-05:00] INFO: Processing directory[C:/chef/log] action create (c:/chef/cache/cookbooks/chef-client/libraries/helpers.rb line 56)
 (up to date)
    * directory[C:/chef] action create[2017-09-18T16:24:25-05:00] INFO: Processing directory[C:/chef] action create (c:/chef/cache/cookbooks/chef-client/libraries/helpers.rb line 56)
 (up to date)
    * windows_task[chef-client] action create[2017-09-18T16:24:25-05:00] INFO: Processing windows_task[chef-client] action create (c:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb line 4
6)


      ================================================================================
      Error executing action `create` on resource 'windows_task[chef-client]'
      ================================================================================

      ArgumentError
      -------------
      invalid date

      Resource Declaration:
      ---------------------
      # In c:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb

       46:   windows_task 'chef-client' do
       47:     run_level :highest
       48:     command "cmd /c \"#{client_cmd}\""
       49:
       50:     user               new_resource.user
       51:     password           new_resource.password
       52:     frequency          new_resource.frequency.to_sym
       53:     frequency_modifier new_resource.frequency_modifier
       54:     start_time         new_resource.start_time || start_time
       55:   end
       56: end

      Compiled Resource:
      ------------------
      # Declared in c:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb:46:in `block in class_from_file'

      windows_task("chef-client") do
        action :create
        default_guard_interpreter :default
        task_name "chef-client"
        declared_type :windows_task
        cookbook_name "chef-client"
        run_level :highest
        command "cmd /c \"C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -s 300\""
        user "SYSTEM"
        password nil
        frequency :minute
        frequency_modifier 30
        start_time "16:54"
        execution_time_limit "PT72H"
        start_day "9/18/2017"
      end

      System Info:
      ------------
      chef_version=13.4.24
      platform=windows
      platform_version=10.0.15063
      ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
      program_name=C:/opscode/chef/bin/chef-client
      executable=C:/opscode/chef/bin/chef-client

[2017-09-18T16:24:25-05:00] INFO: Running queued delayed notifications before re-raising exception

    ================================================================================
    Error executing action `add` on resource 'chef_client_scheduled_task[Chef Client]'
    ================================================================================

    ArgumentError
    -------------
    windows_task[chef-client] (c:/chef/cache/cookbooks/chef-client/resources/scheduled_task.rb line 46) had an error: ArgumentError: invalid date

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/chef-client/recipes/task.rb

     37: chef_client_scheduled_task 'Chef Client' do
     38:   user node['chef_client']['task']['user']
     39:   password node['chef_client']['task']['password']
     40:   frequency node['chef_client']['task']['frequency']
     41:   frequency_modifier lazy { node['chef_client']['task']['frequency_modifier'] }
     42:   start_time node['chef_client']['task']['start_time']
     43:   splay node['chef_client']['splay']
     44:   config_directory node['chef_client']['conf_dir']
     45:   log_directory node['chef_client']['log_dir']
     46:   chef_binary_path node['chef_client']['bin']
     47:   daemon_options node['chef_client']['daemon_options']
     48: end

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/chef-client/recipes/task.rb:37:in `from_file'

    chef_client_scheduled_task("Chef Client") do
      action [:add]
      default_guard_interpreter :default
      declared_type :chef_client_scheduled_task
      cookbook_name "chef-client"
      recipe_name "task"
      user "SYSTEM"
      password nil
      frequency "minute"
      frequency_modifier 30
      start_time nil
      splay "300"
      config_directory "C:/chef"
      log_directory "C:/chef/log"
      chef_binary_path "C:/opscode/chef/bin/chef-client"
      daemon_options []
    end

    System Info:
    ------------
    chef_version=13.4.24
    platform=windows
    platform_version=10.0.15063
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client

[2017-09-18T16:24:25-05:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-09-18T16:24:25-05:00] ERROR: Running exception handlers
Running handlers complete
[2017-09-18T16:24:25-05:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 04 seconds
[2017-09-18T16:24:25-05:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2017-09-18T16:24:25-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-09-18T16:24:25-05:00] FATAL: ArgumentError: chef_client_scheduled_task[Chef Client] (chef-client::task line 37) had an error: ArgumentError: windows_task[chef-client] (c:/chef/cache/cookbooks/che
f-client/resources/scheduled_task.rb line 46) had an error: ArgumentError: invalid date
PS C:\WINDOWS\system32>
```

**Comment by croffe** [comment]
I'm seeing the same issue in Windows 2012 R2.

**Comment by croffe** [comment]
This seems to be an issue since Chef Client 13.4

**Comment by croffe** [comment]
Bill,

This is an issue with the windows_task resource brought into Chef Client 13.4+ which fails when you pass in the start_day with the expected format (MM/DD/YYYY), but it is succeeding with a new format (DD-Mon-YYYY).  I've filed an issue to resolve.

Link below:
https://github.com/chef/chef/issues/6439

**Comment by joaolpalma** [comment]
We just tried to use `strftime("%d-%b-%Y")`, but no success:
```ruby
windows_task 'task' do
  command   "Powershell \"chef-client -L #{File.join(CHEF_LOG_DIR, 'client.log')} -l info\""
  run_level :highest
  frequency :minute
  frequency_modifier 20
  action    :create
  start_day Time.now.strftime("%d-%b-%Y")
end
```

Logs:
```
    ================================================================================
    Error executing action `create` on resource 'windows_task[chef-client]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '-2147467259'
    ---- Begin output of schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "20" /SD "09/26/2017" /ST "12:44:00 PM" /TR "Powershell \"chef-client -L C:/chef/logs/client.log -l info\"" /RU "SYSTEM" /RL "HIGHEST"  ----
    STDOUT:
    STDERR: ERROR: Invalid starttime value.
    ---- End output of schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "20" /SD "09/26/2017" /ST "12:44:00 PM" /TR "Powershell \"chef-client -L C:/chef/logs/client.log -l info\"" /RU "SYSTEM" /RL "HIGHEST"  ----
    Ran schtasks /CREATE /TN "chef-client" /F /SC "minute" /MO "20" /SD "09/26/2017" /ST "12:44:00 PM" /TR "Powershell \"chef-client -L C:/chef/logs/client.log -l info\"" /RU "SYSTEM" /RL "HIGHEST"  returned -2147467259

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/chef-bootstrap/recipes/windows.rb

     42: windows_task 'chef-client' do
     43:   command   "Powershell \"chef-client -L #{File.join(CHEF_LOG_DIR, 'client.log')} -l info\""
     44:   run_level :highest
     45:   frequency :minute
     46:   frequency_modifier 20
     47:   action    :create
     48:   # Fix for https://github.com/chef-cookbooks/chef-client/issues/523
     49:   start_day Time.now.strftime("%d-%b-%Y")
     50: end
     51:

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/chef-bootstrap/recipes/windows.rb:42:in `from_file'

    windows_task("chef-client") do
      action [:create]
      default_guard_interpreter :default
      task_name "chef-client"
      declared_type :windows_task
      cookbook_name "chef-bootstrap"
      recipe_name "windows"
      command "Powershell \"chef-client -L C:/chef/logs/client.log -l info\""
      run_level :highest
      frequency :minute
      execution_time_limit "PT72H"
      frequency_modifier 20
      start_day "26-Sep-2017"
      start_time "12:44:00 PM"
    end

    System Info:
    ------------
    chef_version=13.4.24
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client
```

What is interesting is that the compiled resource is showing the new formatted date, but the STDERR output shows that, in the command used by Chef to create the scheduled task, the old format MM/DD/YYYY is still being used...

**Comment by croffe** [comment]
I think this needs to be corrected at windows_task

**Comment by samefing** [comment]
Seeing the same issue on a Win2016 Server.  Oddly only reports a failure when forcing a chef-client run via WinRM, the automated runs which are initiated by the scheduled task report success.

**Comment by CodingSpiderFox** [comment]
Same here @skares
