### ISSUE TITLE
Bootstrap failed with ERROR: IOError: closed stream

### ISSUE THREAD

**Issue by SrikarshVardhanreddyKolanu** [chef-cookbooks/chef-client#577]
### Cookbook version
[4.2.4]

### Chef-client version
[13.0.118]

### Platform Details
[Red Hat Enterprise Linux Server release 6.9 (Santiago) on AWS]

### Scenario:
[Bootstrapping an instance and can't bootstrap and when checked on the instance it was not able to disable gems using chef-client]

### Steps to Reproduce:
[You can bootstrap a node as below

```knife bootstrap 10.*.*.* -N testnode01 -x ec2-user -i PEMFILE.pem --sudo --bootstrap-template bootstrap.erb --server-url https://chef01.cloud.xxx.com/organizations/xxx -r 'role[base_role]' --bootstrap-vault-json '{"keys":["xxx"]' -E xxx -y```

when am running above bootstrap command observed on the testnode01 as below

```
[root@testnode01 ~]# ps -ef| grep chef-client
ec2-user 30384 30383  0 17:07 pts/0    00:00:00 bash -c sudo -p 'knife sudo password: '  -H sh -c '?chattr -i /etc/hosts?echo "chefServerIp chef01.cloud.xxx.com chef01 " >> /etc/hosts?chmod 644 /etc/hosts?chattr +i /etc/hosts??service ntpd stop?ntpdate 10.82.*.*?service ntpd start??rpm -U http://chef01.cloud.xxx.com/Tool/chef-12.10.24-1.el6.x86_64.rpm?mkdir -p /etc/chef??cat > /etc/chef/client.pem <<EOP?-----BEGIN RSA PRIVATE KEY-----?xxxxxx?-----END RSA PRIVATE KEY-----??EOP?chmod 0600 /etc/chef/client.pem????mkdir -p /etc/chef/trusted_certs?cat > /etc/chef/trusted_certs/chef01_cloud_xxx_com.crt <<'EOP'?-----BEGIN CERTIFICATE-----?xxx?-----END CERTIFICATE-----??EOP????cat > /etc/chef/client.rb <<EOP?chef_server_url  "https://chef01.cloud.xxx.com/organizations/xxx"?validation_client_name "chef-validator"?log_location   STDOUT?node_name "testnode01"?trusted_certs_dir "/etc/chef/trusted_certs"??Ohai::Config[:disabled_plugins] = [ :Passwd ]?EOP??cat > /etc/chef/first-boot.json <<EOP?{"run_list":["role[base_role]"]}?EOP??echo "Starting first Chef Client run..."?chef-client -j /etc/chef/first-boot.json -E edh-preprod-aws'?
root     30385 30384  0 17:07 pts/2    00:00:00 sudo -p knife sudo password:  -H sh -c ?chattr -i /etc/hosts?echo "chefServerIp chef01.cloud.xxx.com chef01 " >> /etc/hosts?chmod 644 /etc/hosts?chattr +i /etc/hosts??service ntpd stop?ntpdate 10.82.*.*?service ntpd start??rpm -U http://chef01.cloud.xxx.com/Tool/chef-12.10.24-1.el6.x86_64.rpm?mkdir -p /etc/chef??cat > /etc/chef/client.pem <<EOP?-----BEGIN RSA PRIVATE KEY-----?xxx?-----END RSA PRIVATE KEY-----??EOP?chmod 0600 /etc/chef/client.pem????mkdir -p /etc/chef/trusted_certs?cat > /etc/chef/trusted_certs/chef01_cloud_xxx_com.crt <<EOP?-----BEGIN CERTIFICATE-----?xxx?-----END CERTIFICATE-----??EOP????cat > /etc/chef/client.rb <<EOP?chef_server_url  "https://chef01.cloud.xxx.com/organizations/xxx"?validation_client_name "chef-validator"?log_location   STDOUT?node_name "testnode01"?trusted_certs_dir "/etc/chef/trusted_certs"??Ohai::Config[:disabled_plugins] = [ :Passwd ]?EOP??cat > /etc/chef/first-boot.json <<EOP?{"run_list":["role[base_role]"]}?EOP??echo "Starting first Chef Client run..."?chef-client -j /etc/chef/first-boot.json -E edh-preprod-aws
root     30404 30385  0 17:07 pts/2    00:00:00 /opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -j /etc/chef/first-boot.json -E edh-preprod-aws
root     30458 30404  0 17:07 pts/2    00:00:01 chef-client worker: ppid=30404;start=17:07:34;
root     30854 30839  0 17:12 pts/4    00:00:00 grep chef-client
```

Then tried to run 

```
/opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -j /etc/chef/first-boot.json -E edh-preprod-aws 
```

from the node then observed the below

```
/opt/chef/embedded/bin/ruby --disable-gems /usr/bin/chef-client -j /etc/chef/first-boot.json -E edh-preprod-aws
Starting Chef Client, version 13.0.118
resolving cookbooks for run list: ["edh_yum", "edh_chef_client", "edh_push-jobs", "edh_centrify-kerberos", "edh_cfgdat"]
Synchronizing Cookbooks:
  - edh_yum (0.1.0)
  - edh_chef_client (0.1.0)
  - yum (3.8.2)
  - chef-client (4.2.4)
  - cron (6.1.1)
  - logrotate (1.9.2)
  - windows (1.37.0)
  - chef_handler (3.0.3)
  - edh_push-jobs (0.2.0)
  - push-jobs (5.2.0)
  - runit (3.0.0)
  - packagecloud (0.3.0)
  - yum-epel (2.1.2)
  - compat_resource (12.19.0)
  - chef-ingredient (0.19.0)
  - edh_centrify-kerberos (0.1.0)
  - chef-vault_wrapper (0.1.0)
  - chef-vault (3.0.0)
  - edh_cfgdat (1.0.1)
Installing Cookbook Gems:
Running handlers:
[2018-06-21T18:07:15+00:00] ERROR: Running exception handlers
Running handlers complete
[2018-06-21T18:07:15+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 06 minutes 02 seconds
[2018-06-21T18:07:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-06-21T18:07:15+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-06-21T18:07:15+00:00] ERROR: Expected process to exit with [0], but received '17'
---- Begin output of bundle install ----
STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching source index from https://www.rubygems.org/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://www.rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://www.rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://www.rubygems.org/
Could not fetch specs from https://www.rubygems.org/
STDERR:
---- End output of bundle install ----
Ran bundle install returned 17
[2018-06-21T18:07:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

]

### Expected Result:
[
It works fine with chef client version 12.10.24 as below and same I expect to be done with 13.0.118

```
Creating new client for testnode01
Creating new node for testnode01
Connecting to 10.*.*.*
10.*.*.* Shutting down ntpd: [60G[[0;32m  OK  [0;39m]
10.*.*.*  6 Jun 20:41:45 ntpdate[36513]: adjust time server 10.82.254.110 offset -0.000141 sec
10.*.*.* Starting ntpd: [60G[[0;32m  OK  [0;39m]
10.*.*.* warning: /var/tmp/rpm-tmp.5vQq2C: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
10.*.*.* 	package chef-12.10.24-1.el6.x86_64 is already installed
10.*.*.* Starting first Chef Client run...
10.*.*.* [2018-06-06T20:41:46+00:00] WARN: Ohai::Config[:disabled_plugins] is set. Ohai::Config[:disabled_plugins] is deprecated and will be removed in future releases of ohai. Use ohai.disabled_plugins in your configuration file to configure :disabled_plugins for ohai.
10.*.*.* Starting Chef Client, version 12.10.24[0m
10.*.*.* resolving cookbooks for run list: ["resolver", "edh_yum", "edh_chef_client", "edh_push-jobs", "edh_centrify-kerberos", "edh_cfgdat"][0m
10.*.*.* Synchronizing Cookbooks:[0m
10.*.*.*   - resolver (1.3.0)[0m
10.*.*.*   - edh_yum (0.1.0)[0m
10.*.*.*   - yum (3.8.2)[0m
10.*.*.*   - edh_chef_client (0.1.0)[0m
10.*.*.*   - chef-client (4.2.4)[0m
10.*.*.*   - cron (1.7.6)[0m
10.*.*.*   - logrotate (1.9.2)[0m
10.*.*.*   - windows (1.37.0)[0m
10.*.*.*   - chef_handler (1.1.8)[0m
10.*.*.*   - edh_push-jobs (0.2.0)[0m
10.*.*.*   - push-jobs (3.2.0)[0m
10.*.*.*   - runit (3.0.0)[0m
10.*.*.*   - packagecloud (0.2.5)[0m
10.*.*.*   - yum-epel (1.0.2)[0m
10.*.*.*   - chef-ingredient (0.19.0)[0m
10.*.*.*   - compat_resource (12.16.1)[0m
10.*.*.*   - chef-vault_wrapper (0.1.0)[0m
10.*.*.*   - chef-vault (1.3.0)[0m
10.*.*.*   - edh_cfgdat (1.0.1)[0m
10.*.*.*   - edh_centrify-kerberos (0.1.0)[0m
10.*.*.* Installing Cookbook Gems:[0m
10.*.*.* Compiling Cookbooks...[0m
10.*.*.* [2018-06-06T20:41:48+00:00] WARN: resolver::default requires that attribute ['resolver']['nameservers'] is set.
10.*.*.* Recipe: edh_push-jobs::default[0m
10.*.*.*   * chef_gem[mixlib-install] action upgrade (up to date)
10.*.*.* [2018-06-06T20:41:50+00:00] WARN: Cloning resource attributes for directory[/etc/chef] from prior resource (CHEF-3694)
10.*.*.* [2018-06-06T20:41:50+00:00] WARN: Previous directory[/etc/chef]: /var/chef/cache/cookbooks/chef-client/libraries/helpers.rb:53:in `rescue in block in create_directories'
10.*.*.* [2018-06-06T20:41:50+00:00] WARN: Current  directory[/etc/chef]: /var/chef/cache/cookbooks/push-jobs/recipes/config.rb:24:in `from_file'
10.*.*.* Recipe: chef-vault_wrapper::default[0m
10.*.*.*   * chef_gem[chef-vault] action install (up to date)
10.*.*.* [2018-06-06T20:41:50+00:00] WARN: Cloning resource attributes for chef_gem[chef-vault] from prior resource (CHEF-3694)
10.*.*.* [2018-06-06T20:41:50+00:00] WARN: Previous chef_gem[chef-vault]: /var/chef/cache/cookbooks/chef-vault_wrapper/recipes/default.rb:9:in `from_file'
10.*.*.* [2018-06-06T20:41:50+00:00] WARN: Current  chef_gem[chef-vault]: /var/chef/cache/cookbooks/chef-vault/recipes/default.rb:21:in `from_file'
10.*.*.* Recipe: chef-vault::default[0m
```
]

### Actual Result:
[
```
Creating new client for testnode01
Creating new node for testnode01
Connecting to 10.*.*.*
10.*.*.* Shutting down ntpd: [60G[[0;32m  OK  [0;39m]
10.*.*.* 21 Jun 17:07:32 ntpdate[30427]: adjust time server 10.82.*.* offset 0.000686 sec
10.*.*.* Starting ntpd: [60G[[0;32m  OK  [0;39m]
10.*.*.* warning: /var/tmp/rpm-tmp.MkPrBz: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
10.*.*.* 	package chef-13.0.118-1.el6.x86_64 (which is newer than chef-12.10.24-1.el6.x86_64) is already installed
10.*.*.* Starting first Chef Client run...
10.*.*.* Starting Chef Client, version 13.0.118[0m
10.*.*.* resolving cookbooks for run list: ["edh_yum", "edh_chef_client", "edh_push-jobs", "edh_centrify-kerberos", "edh_cfgdat"][0m
10.*.*.* Synchronizing Cookbooks:[0m
10.*.*.*   - edh_yum (0.1.0)[0m
10.*.*.*   - edh_chef_client (0.1.0)[0m
10.*.*.*   - yum (3.8.2)[0m
10.*.*.*   - chef-client (4.2.4)[0m
10.*.*.*   - cron (6.1.1)[0m
10.*.*.*   - logrotate (1.9.2)[0m
10.*.*.*   - windows (1.37.0)[0m
10.*.*.*   - chef_handler (3.0.3)[0m
10.*.*.*   - edh_push-jobs (0.2.0)[0m
10.*.*.*   - push-jobs (5.2.0)[0m
10.*.*.*   - runit (3.0.0)[0m
10.*.*.*   - packagecloud (0.3.0)[0m
10.*.*.*   - yum-epel (2.1.2)[0m
10.*.*.*   - compat_resource (12.19.0)[0m
10.*.*.*   - chef-ingredient (0.19.0)[0m
10.*.*.*   - edh_centrify-kerberos (0.1.0)[0m
10.*.*.*   - chef-vault_wrapper (0.1.0)[0m
10.*.*.*   - chef-vault (3.0.0)[0m
10.*.*.*   - edh_cfgdat (1.0.1)[0m
10.*.*.* Installing Cookbook Gems:[0m
ERROR: IOError: closed stream
Build step 'Execute shell' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

```
cat /var/chef/cache/chef-stacktrace.out
Generated at 2018-06-21 18:07:15 +0000
Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '17'
---- Begin output of bundle install ----
STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching source index from https://www.rubygems.org/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://www.rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://www.rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://www.rubygems.org/
Could not fetch specs from https://www.rubygems.org/
STDERR:
---- End output of bundle install ----
Ran bundle install returned 17
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/mixin/shell_out.rb:120:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook/gem_installer.rb:62:in `block (2 levels) in install'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook/gem_installer.rb:52:in `open'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook/gem_installer.rb:52:in `block in install'
/opt/chef/embedded/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook/gem_installer.rb:51:in `install'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/cookbook/cookbook_collection.rb:60:in `install_gems'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/policy_builder/expand_node_object.rb:86:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:513:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/client.rb:281:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.118/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
```
]

Also tried to upgrade some cookbooks but didn't worked

**Comment by SrikarshVardhanreddyKolanu** [comment]
Could anyone please take a look on this

**Comment by bageorge** [comment]
I am also getting similar error all of a sudden. My chef-client version is 14.8.12 and ruby version is 2.5.3p105. My use case is executing a shell script on a remote VM using ssh session.
Any suggestions ?

**Comment by lamont-granquist** [comment]
This bug report has nothing to do with the chef-client cookbook and is due to one of the other cookbooks in the run list having a `gem` statement in the metadata.  Combined with rubygems.org not be reachable.  It has nothing to do with this repo and is more of a question for discord/stackoverflow/slack/etc.
